/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/miscellaneous/AppLink.vue')['default']
    BackToTop: typeof import('./src/components/miscellaneous/BackToTop.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LoginCard: typeof import('./src/components/authentication/LoginCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OverviewCard: typeof import('./src/components/dashboard/OverviewCard.vue')['default']
    PendingApplications: typeof import('./src/components/dashboard/PendingApplications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteLists: typeof import('./src/components/dashboard/SiteLists.vue')['default']
    TotalData: typeof import('./src/components/dashboard/TotalData.vue')['default']
  }
}
